sudo: required

language: go

go:
  - 1.x

git:
  depth: 1

env:
  global:
    - UPXVER="3.95"

install:
  - go get -d -v ./...
  - echo "Installing upx .."
  - "{ [ -f upx/${UPXVER}/upx ]; } ||
      { curl -OL https://github.com/upx/upx/releases/download/v${UPXVER}/upx-${UPXVER}-amd64_linux.tar.xz;
        tar xvf upx-${UPXVER}-amd64_linux.tar.xz;
        mkdir -p upx;
        mv upx-${UPXVER}-amd64_linux upx/${UPXVER};
      }"
  - export PATH="${TRAVIS_BUILD_DIR}/upx/${UPXVER}/:${PATH}"

script:
  - go get github.com/mitchellh/gox
  - GOOS=windows go get -d -v ./...
  - gox -verbose -output docker-log-loki-{{.OS}}-{{.Arch}} -os "linux" -arch "amd64 386 arm arm64" -ldflags "-s -w -X main.Version=${TRAVIS_TAG} -X main.buildTime=`date -u '+%Y-%m-%d_%I:%M:%S%p'` -X main.commitId=${TRAVIS_COMMIT}"
  - upx docker-log-loki-linux-*

deploy:
  provider: releases
  api_key:
    secure: "h00Qu/dM/sbRy6+aewDSa+G3XJKIfxAuH4ME++CXOEc44ytWbY0ABWuzkRC54eQ60bX7unyvT6urSuyddOnYzJ9zmuAlL3vOrLiuSqd46lXjSsxhmr0AJqNS84OxMN7RRBLmrZcULkLQQ83+xsmRW6OuFZBJXmM8vyhCLGzdpktHxOhl19JoRKq4R0SX8+Hk4ETKAVhhjQVQJ/qIIdPEScz93FKFfKqpmNFg9WlDp163jZo+KWUhQTDlKCZ4xp3SQ9DWZPUpmUvedc6LksWouDwR4KCm71erfgpYY99YLEb7ZqVt3p1j1/4xHEAvpXgDmVTrd8RKNmcgcjV1Hdz5gZTfoYXnqJIj8KUHZytXUXmZWDFnoNvqKcEFEpNTnDlbMH/+pN+ok1KmdBrz7XY8AKKEHIBAheeHSpWdlJEVGa/AT3yGvdRyApqra3jnnwr5yrEhW9rIGrrygn/icZryvUJqk5P+ZYN6CuZYIer+dmZy1kEOjhd9B2tmBlsdh7aQHnzUfZ8FAndwxqCuJ9uMVkL/BmaVRfE3Rc9ctd7hbLWkGwduahOhW9HRzbNsZTd5eekdyv1DQ6xF+YKhq7VQLpM85gaa6pJ+Cjxp0kVpHPcZADLXuJ43iFKgfRhovsvZX2iwzyOJ8f6a+lpOrnwqy6zYubxzoatPGg96FtobtIM="
  skip_cleanup: true
  file:
    - docker-log-loki-linux-amd64
    - docker-log-loki-linux-386
    - docker-log-loki-linux-arm
    - docker-log-loki-linux-arm64
  on:
    repo: lfdominguez/docker_log_driver_loki
    tags: true